# Generated by Django 4.2.1 on 2023-05-15 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bakedcookie",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bakedcookie",
                to="bakery.cookie",
            ),
        ),
        migrations.AlterField(
            model_name="dough",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dough",
                to="bakery.cookie",
            ),
        ),
        migrations.AlterField(
            model_name="grocery",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to="bakery.cookie",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store",
                to="bakery.cookie",
            ),
        ),
    ]
