# Generated by Django 4.2.1 on 2023-05-15 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0002_alter_bakedcookie_cookie_alter_dough_cookie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bakedcookie",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bakedcookie_set",
                to="bakery.cookie",
            ),
        ),
        migrations.AlterField(
            model_name="dough",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dough_set",
                to="bakery.cookie",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_set",
                to="bakery.cookie",
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="cookie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_set",
                to="bakery.cookie",
            ),
        ),
    ]
