# Generated by Django 4.2.4 on 2023-08-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0007_alter_cookie_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookieimage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
