# Generated by Django 4.2.4 on 2023-08-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0008_cookieimage_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cookieimage",
            name="is_active",
        ),
        migrations.AddField(
            model_name="cookie",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
