# Generated by Django 4.2.4 on 2023-09-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0009_remove_cookieimage_is_active_cookie_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookie",
            name="slug",
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
