# Generated by Django 4.2.4 on 2023-09-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0010_cookie_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookie",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
