# Generated by Django 4.2.4 on 2023-12-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0012_ingredient_recipeinstruction_alter_grocery_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
