# Generated by Django 4.2.4 on 2023-12-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0013_recipeingredient_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="grocery",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
