# Generated by Django 4.2.4 on 2023-12-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0014_grocery_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grocery",
            name="order_link",
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
