# Generated by Django 4.2.4 on 2024-01-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bakery",
            "0016_remove_recipe_ingredients_remove_recipe_instructions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="bakery.RecipeIngredient", to="bakery.ingredient"
            ),
        ),
    ]
