# Generated by Django 4.2.4 on 2024-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0017_recipe_ingredients"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="description",
            new_name="notes",
        ),
        migrations.AddField(
            model_name="cookie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
