# Generated by Django 4.2.4 on 2024-01-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0018_rename_description_recipe_notes_cookie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookieimage",
            name="cookie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="bakery.cookie",
            ),
        ),
    ]
