# Generated by Django 4.2.4 on 2024-01-31 21:48

import bakery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0019_alter_cookieimage_cookie"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookie",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="bakery/images",
                validators=[bakery.models.validate_file_size],
            ),
        ),
        migrations.DeleteModel(
            name="CookieImage",
        ),
    ]
