# Generated by Django 4.2.4 on 2024-02-07 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0021_alter_recipe_cookie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="recipe",
        ),
        migrations.RemoveField(
            model_name="recipeinstruction",
            name="recipe",
        ),
        migrations.AddField(
            model_name="cookie",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="cookie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="bakery.cookie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipeinstruction",
            name="cookie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructions",
                to="bakery.cookie",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
