# Generated by Django 4.2.1 on 2023-05-10 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bakedcookie",
            old_name="location",
            new_name="shelf",
        ),
        migrations.RenameField(
            model_name="dough",
            old_name="location",
            new_name="shelf",
        ),
        migrations.AddField(
            model_name="grocery",
            name="shelf",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="bakery.shelf",
            ),
        ),
    ]
