# Generated by Django 4.2.1 on 2023-05-21 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0003_alter_bakedcookie_cookie_alter_dough_cookie_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CookieImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="bakery/images")),
                (
                    "cookie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="bakery.cookie",
                    ),
                ),
            ],
        ),
    ]
