# Generated by Django 4.2.4 on 2023-08-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0005_alter_bakedcookie_quantity_alter_cookieimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dough",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="grocery",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="store",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
