# Generated by Django 4.2.4 on 2023-08-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0006_alter_dough_quantity_alter_grocery_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookie",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
